name: Zola on GitHub Pages

on: workflow_dispatch

#on: 
 #push:
  #branches:
   #- main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build and deploy
      uses: siddhantladdha/zola-deploy-action@$58a04003e27da65b50920f331d3f21b60824d85a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
